version: '3'
services:
  shiftrio:
    build:
      context: .
      dockerfile: ./shiftrio/Dockerfile
    container_name: shiftrio-container
    ports:
        - 1883:1883
        - 1884:1884
    networks:
      - mqtt_network
  python3:
    build:
      context: .
      dockerfile: ./python/Dockerfile
    container_name: python3-container
    working_dir: /python_ws
    tty: true
    volumes:
    - ./python/python_ws:/python_ws
    networks:
      - mqtt_network
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    environment:
      - GF_INSTALL_PLUGINS=grafana-mqtt-datasource
    ports:
      - 3000:3000
    volumes:
      - ./grafana/data:/var/lib/grafana
    networks:
      - mqtt_network
networks:
  mqtt_network:
    driver: bridge